angular.module('starter.controllers', []).controller('DashCtrl', ($scope, $rootScope,  $state,  $log, Renderings, Views, Floorplans, Videos, Webcams, Presentations, ActiveBuilding) -> 
  $scope.presentations = {"Presentations": Presentations.all()}
  $scope.factories = {"Videos" : Videos.all(),  "Floor Plans" : Floorplans.all(), "Rendering":Renderings.all(), "Views" : Views.all(),  "Webcams" : Webcams.all(),}
  $scope.activeBuilding = ActiveBuilding
  $scope.state = $state;

  ###
  # if given group is the selected group, deselect it
  # else, select the given group
  ###

  $scope.toggleGroup = (group) ->
    if $scope.isGroupShown(group)
      $scope.shownGroup = null
    else
      $scope.shownGroup = group
    return

  $scope.isGroupShown = (group) ->
    $scope.shownGroup == group    
  
  $scope.openPres = (presId) ->
    window.location = '#/tab/presentations/' + presId
    window.location.reload()
    return

# ---
# generated by js2coffee 2.1.0    

).controller('VideoDetailCtrl', ($scope, $stateParams, Videos) ->
  $scope.video = Videos.get($stateParams.modelId)
  return
).controller('FloorplanDetailCtrl', ($scope, $stateParams, Floorplans) ->
  $scope.floorplan = Floorplans.get($stateParams.modelId)
  return
).controller('VideoDetailCtrl', ($scope, $stateParams, Webcams) ->
  $scope.webcam = Webcams.get($stateParams.modelId)
  return
).controller('VideoDetailCtrl', ($scope, $stateParams, Presentations) ->
  $scope.presentation = Presentations.get($stateParams.modelId)
  return
).controller('PresentationCtrl', ($scope,$log, $stateParams, Presentations) ->
  $scope.presentation = Presentations.get($stateParams.presentationId)
  $scope.slides = Presentations.getSlides($stateParams.presentationId)
  $scope.presentation_name = $scope.presentation.name
  $scope.project_name = $scope.presentation.project_name
  $scope.postSlide = (slideId) ->
    $log.debug("FUCKYES "+ slideId)
  $scope.alertMe = ()->
    $log.debug("FUCK")    
  return
).controller('VideoPlayerCtrl', ($scope, $sce, $log, $stateParams, Videos) ->
  $scope.video = Videos.get($stateParams.videoId)
  #$log.debug($scope.video.recording);
  $scope.recording = $sce.trustAsResourceUrl($scope.video.recording)
  
  $scope.trustSrc = (src) ->
    $scope.videos = $sce.getTrustedResourceUrl(src);


  $scope.postVideoId = (videoId) ->
    $log.debug("FUCKYES "+ videoId)
  
  $scope.alertMe = ()->
    $log.debug("FUCK")    
  return
).controller('ChatsCtrl', ($scope, Chats) ->
  # With the new view caching in Ionic, Controllers are only called
  # when they are recreated or on app start, instead of every page change.
  # To listen for when this page is active (for example, to refresh data),
  # listen for the $ionicView.enter event:
  #
  #$scope.$on('$ionicView.enter', function(e) {
  #});
  $scope.chats = Chats.all()

  $scope.remove = (chat) ->
    Chats.remove chat
    return

  return
).controller('ChatDetailCtrl', ($scope, $stateParams, Chats) ->
  $scope.chat = Chats.get($stateParams.chatId)
  return
).controller('AccountCtrl', ($scope) ->
  $scope.settings = enableFriends: true
  return
).controller('TopMenuCtrl', ($scope,  Buildings,ActiveBuilding, $log) ->
  $scope.activeBuilding = ActiveBuilding
  $scope.buildings = Buildings.all()
  $scope.templatePath = "templates/menu/building_menu.html"
  $scope.bld_style="margin-top: 5px"
  $scope.building_is = (code, name) ->
    if code == name
    # if name == "200 Mass"
      return true
  $scope.getTemplate = (name) ->
    Buildings.getTemplate(name)
  $scope.setActiveBuilding = (name)->
    $scope.activeBuilding.name = name
  $scope.toggleTopMenu = ->
    bld = document.getElementById('building_wrap')
    menu = document.getElementById('ionTopMenu')
    panes = document.getElementsByTagName('ion-view')
    for pane in panes
      menu.style.height = pane.style.top = if menu.offsetHeight == 4 then '300px' else '4px'
    if menu.style.height == "4px"
      $scope.bld_style = "margin-top: 5px"
    else
      $scope.bld_style = "margin-top: 50px"
    return 
)  
# ---
# generated by js2coffee 2.1.0